<?php if(function_exists("register_field_group"))
{
	register_field_group(array (
		'id' => 'acf_masterclass-fields',
		'title' => 'Masterclass Fields',
		'fields' => array (
			array (
				'key' => 'field_577187c3e24e0',
				'label' => 'Details',
				'name' => '',
				'type' => 'tab',
			),
			array (
				'key' => 'field_576f94647c791',
				'label' => 'Day & Time',
				'name' => 'mc_dates',
				'type' => 'repeater',
				'sub_fields' => array (
					array (
						'key' => 'field_576f99bd5459c',
						'label' => 'Dates',
						'name' => 'mc_date',
						'type' => 'date_picker',
						'column_width' => 50,
						'date_format' => 'yymmdd',
						'display_format' => 'mm/dd/yy',
						'first_day' => 0,
					),
					array (
						'key' => 'field_576f9a7188f7c',
						'label' => 'Time',
						'name' => 'mc_time',
						'type' => 'text',
						'column_width' => 50,
						'default_value' => '',
						'placeholder' => '00:00am – 00:00pm',
						'prepend' => '',
						'append' => '',
						'formatting' => 'none',
						'maxlength' => '',
					),
				),
				'row_min' => 1,
				'row_limit' => '',
				'layout' => 'table',
				'button_label' => 'Add Date',
			),
			array (
				'key' => 'field_577188e1efc3e',
				'label' => 'Place',
				'name' => 'mc_location',
				'type' => 'textarea',
				'instructions' => 'Recommended displayed format:<br/>
	<i>Shoreline Amphitheatre<br/>
	1 Amphitheatre Pkwy<br/>
	Mountain View, CA 94043</i>',
				'default_value' => '',
				'placeholder' => '',
				'maxlength' => '',
				'rows' => 2,
				'formatting' => 'br',
			),
			array (
				'key' => 'field_577187f1e24e1',
				'label' => 'About',
				'name' => '',
				'type' => 'tab',
			),
			array (
				'key' => 'field_5771880ce24e2',
				'label' => 'Description',
				'name' => 'mc_description',
				'type' => 'wysiwyg',
				'default_value' => '',
				'toolbar' => 'basic',
				'media_upload' => 'yes',
			),
			array (
				'key' => 'field_57718825e24e3',
				'label' => 'Button',
				'name' => '',
				'type' => 'tab',
			),
			array (
				'key' => 'field_57718837e24e4',
				'label' => 'CTA',
				'name' => 'mc_cta',
				'type' => 'repeater',
				'instructions' => 'Maximum 3 CTA buttons. Recommended CTA text: <i>RSVP, Learn more, Contact Ruth, Purchase Tickets</i>.',
				'sub_fields' => array (
					array (
						'key' => 'field_57718845e24e5',
						'label' => 'CTA Text',
						'name' => 'mc_cta_text',
						'type' => 'text',
						'column_width' => 25,
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'formatting' => 'none',
						'maxlength' => '',
					),
					array (
						'key' => 'field_57718864e24e6',
						'label' => 'CTA Link',
						'name' => 'mc_cta_link',
						'type' => 'text',
						'column_width' => '',
						'default_value' => 'http://',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'formatting' => 'html',
						'maxlength' => '',
					),
				),
				'row_min' => '',
				'row_limit' => 3,
				'layout' => 'table',
				'button_label' => 'Add Row',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'masterclass',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'acf_after_title',
			'layout' => 'default',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 0,
	));
	register_field_group(array (
		'id' => 'acf_service-fields',
		'title' => 'Service Fields',
		'fields' => array (
			array (
				'key' => 'field_576c7bf85ae5a',
				'label' => 'Excerpt',
				'name' => 'excerpt',
				'type' => 'textarea',
				'instructions' => 'Used as excerpt for homepage. Recommended 35 word maximum.',
				'required' => 1,
				'default_value' => '',
				'placeholder' => '',
				'maxlength' => '',
				'rows' => 2,
				'formatting' => 'br',
			),
			array (
				'key' => 'field_576c78a033ea6',
				'label' => 'Service',
				'name' => 'service_repeater',
				'type' => 'repeater',
				'instructions' => 'Recommended add maximum 2 sections.',
				'sub_fields' => array (
					array (
						'key' => 'field_576c78c733ea7',
						'label' => 'Section Title',
						'name' => 'section_title',
						'type' => 'text',
						'required' => 1,
						'column_width' => 100,
						'default_value' => '',
						'placeholder' => 'Enter title here',
						'prepend' => '',
						'append' => '',
						'formatting' => 'none',
						'maxlength' => '',
					),
					array (
						'key' => 'field_576c790b33ea8',
						'label' => 'Section Content',
						'name' => 'section_content',
						'type' => 'wysiwyg',
						'required' => 1,
						'column_width' => 100,
						'default_value' => '',
						'toolbar' => 'full',
						'media_upload' => 'yes',
					),
					array (
						'key' => 'field_576c793233ea9',
						'label' => 'Section Type',
						'name' => 'section_type',
						'type' => 'select',
						'column_width' => '',
						'choices' => array (
							'default' => 'Default (Approach, Credentials)',
							'quote' => 'Quote Block (Diagnosis)',
							'slider' => 'Slider Block (Services)',
						),
						'default_value' => '',
						'allow_null' => 0,
						'multiple' => 0,
					),
				),
				'row_min' => 1,
				'row_limit' => 3,
				'layout' => 'row',
				'button_label' => 'Add Section',
			),
			array (
				'key' => 'field_576c7a248ae22',
				'label' => 'Testimonials',
				'name' => 'testimonials_repeater',
				'type' => 'repeater',
				'instructions' => 'Recommended maximum 5 testimonials.',
				'sub_fields' => array (
					array (
						'key' => 'field_576c7a418ae23',
						'label' => 'Name',
						'name' => 'name',
						'type' => 'text',
						'instructions' => 'Recommended format Name – Title (i.g. Jane Doe – Singer)',
						'required' => 1,
						'column_width' => 100,
						'default_value' => '',
						'placeholder' => 'Name – Title',
						'prepend' => '',
						'append' => '',
						'formatting' => 'none',
						'maxlength' => '',
					),
					array (
						'key' => 'field_576c7a758ae24',
						'label' => 'Link',
						'name' => 'link',
						'type' => 'text',
						'column_width' => '',
						'default_value' => '',
						'placeholder' => 'Website Url',
						'prepend' => '',
						'append' => '',
						'formatting' => 'none',
						'maxlength' => '',
					),
					array (
						'key' => 'field_576c7aea8ae25',
						'label' => 'Testimonial',
						'name' => 'testimonial',
						'type' => 'textarea',
						'column_width' => '',
						'default_value' => '',
						'placeholder' => '',
						'maxlength' => '',
						'rows' => 5,
						'formatting' => 'br',
					),
				),
				'row_min' => 1,
				'row_limit' => 5,
				'layout' => 'row',
				'button_label' => 'Add Testimonial',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'service',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'no_box',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 0,
	));
	register_field_group(array (
		'id' => 'acf_two-columns',
		'title' => 'Two Columns',
		'fields' => array (
			array (
				'key' => 'field_578d966f66b37',
				'label' => 'Second Column',
				'name' => 'second_col',
				'type' => 'wysiwyg',
				'instructions' => '<b>Recommended Form Area</b>
	http://localhost:8888/wordpress/wp-admin/admin.php?page=wpcf7',
				'default_value' => '',
				'toolbar' => 'full',
				'media_upload' => 'yes',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'page_template',
					'operator' => '==',
					'value' => 'page-two-col.php',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'no_box',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 0,
	));
}
?>